# Generated by Django 4.0.3 on 2022-03-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_play_app_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='name4',
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(default='Blank', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='Blank', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(default='Blank', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='listing',
            name='rarity',
            field=models.CharField(default='Blank', max_length=32),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(default='Blank', max_length=32),
        ),
    ]
