# Generated by Django 4.0.3 on 2022-03-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_play_app_api', '0002_remove_listing_name1_remove_listing_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
